name: Release

on:
  push:
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run build
      - run: npm test
      - name: Preparar wasm
        run: cp node_modules/@myriaddreamin/typst-ts-web-compiler/pkg/typst_ts_web_compiler_bg.wasm dist/typst.wasm
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/main.js
            dist/manifest.json
            dist/styles.css
            dist/typst.wasm
